from pydantic import BaseModel, EmailStr, Field
from typing import Optional

# 1. Understanding Pydantic vs SQLAlchemy
# - SQLAlchemy Models (models.py) define how data is stored in the Database (columns, constraints).
# - Pydantic Schemas (schemas.py) define the format and rules for data entering or leaving the API (data validation).

# 2. Base Schema
# Contains fields common to both reading and writing student data.
class StudentBase(BaseModel):
    name: str = Field(..., min_length=2, max_length=50, description="Full name of the student")
    email: EmailStr = Field(..., description="Unique email address of the student")
    age: int = Field(..., gt=0, lt=120, description="Age must be a positive integer between 1 and 120")
    grade: str = Field(..., min_length=1, description="Grade of the student (e.g. A, 10th Grade)")

# 3. Create Schema
# Used when adding a new student via POST /students.
# It inherits all fields from StudentBase. In a real-world app, you might add validations or hidden fields here.
class StudentCreate(StudentBase):
    pass

# 4. Update Schema
# Used when updating a student's info via PUT /students/{id}.
# Every field is optional. This allows the user to update just the name, just the age, or everything.
class StudentUpdate(BaseModel):
    name: Optional[str] = Field(None, min_length=2, max_length=50)
    email: Optional[EmailStr] = Field(None)
    age: Optional[int] = Field(None, gt=0, lt=120)
    grade: Optional[str] = Field(None, min_length=1)

# 5. Response Schema
# Defines the format of the data returned by the API to the client.
# Adds the 'id' field which is generated by the database and is not present in creation schemas.
class Student(StudentBase):
    id: int

    # Config class tells Pydantic to read data even if it's not a standard dict.
    # In FastAPI, we retrieve SQLAlchemy model objects (which are Python objects, not dicts).
    # 'from_attributes = True' (formerly 'orm_mode = True') tells Pydantic to read database properties directly from objects.
    class Config:
        from_attributes = True
